/* The following code was generated by JFlex 1.6.1 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>LexicalAnalyser.flex</tt>
 */
class LexicalAnalyser {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\11\1\4\1\2\1\42\1\43\1\3\16\11\4\0\1\4\1\5"+
    "\2\0\1\6\3\0\1\33\1\34\1\31\1\37\1\32\1\36\1\10"+
    "\1\40\12\7\3\0\1\35\3\0\1\16\1\6\1\1\1\22\1\20"+
    "\1\24\1\15\1\26\1\23\2\6\1\27\1\17\1\21\1\14\1\12"+
    "\1\41\1\13\1\30\1\25\6\6\4\0\1\6\1\0\2\6\1\1"+
    "\1\1\26\6\4\0\6\11\1\44\32\11\2\0\4\6\4\0\1\6"+
    "\2\0\1\11\7\0\1\6\4\0\1\6\5\0\27\6\1\0\37\6"+
    "\1\0\u01ca\6\4\0\14\6\16\0\5\6\7\0\1\6\1\0\1\6"+
    "\21\0\160\11\5\6\1\0\2\6\2\0\4\6\10\0\1\6\1\0"+
    "\3\6\1\0\1\6\1\0\24\6\1\0\123\6\1\0\213\6\1\0"+
    "\5\11\2\0\236\6\11\0\46\6\2\0\1\6\7\0\47\6\7\0"+
    "\1\6\1\0\55\11\1\0\1\11\1\0\2\11\1\0\2\11\1\0"+
    "\1\11\10\0\33\6\5\0\3\6\15\0\5\11\6\0\1\6\4\0"+
    "\13\11\5\0\53\6\37\11\4\0\2\6\1\11\143\6\1\0\1\6"+
    "\10\11\1\0\6\11\2\6\2\11\1\0\4\11\2\6\12\11\3\6"+
    "\2\0\1\6\17\0\1\11\1\6\1\11\36\6\33\11\2\0\131\6"+
    "\13\11\1\6\16\0\12\11\41\6\11\11\2\6\4\0\1\6\5\0"+
    "\26\6\4\11\1\6\11\11\1\6\3\11\1\6\5\11\22\0\31\6"+
    "\3\11\104\0\1\6\1\0\13\6\67\0\33\11\1\0\4\11\66\6"+
    "\3\11\1\6\22\11\1\6\7\11\12\6\2\11\2\0\12\11\1\0"+
    "\7\6\1\0\7\6\1\0\3\11\1\0\10\6\2\0\2\6\2\0"+
    "\26\6\1\0\7\6\1\0\1\6\3\0\4\6\2\0\1\11\1\6"+
    "\7\11\2\0\2\11\2\0\3\11\1\6\10\0\1\11\4\0\2\6"+
    "\1\0\3\6\2\11\2\0\12\11\4\6\7\0\1\6\5\0\3\11"+
    "\1\0\6\6\4\0\2\6\2\0\26\6\1\0\7\6\1\0\2\6"+
    "\1\0\2\6\1\0\2\6\2\0\1\11\1\0\5\11\4\0\2\11"+
    "\2\0\3\11\3\0\1\11\7\0\4\6\1\0\1\6\7\0\14\11"+
    "\3\6\1\11\13\0\3\11\1\0\11\6\1\0\3\6\1\0\26\6"+
    "\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\11\1\6\10\11"+
    "\1\0\3\11\1\0\3\11\2\0\1\6\17\0\2\6\2\11\2\0"+
    "\12\11\1\0\1\6\17\0\3\11\1\0\10\6\2\0\2\6\2\0"+
    "\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\11\1\6"+
    "\7\11\2\0\2\11\2\0\3\11\10\0\2\11\4\0\2\6\1\0"+
    "\3\6\2\11\2\0\12\11\1\0\1\6\20\0\1\11\1\6\1\0"+
    "\6\6\3\0\3\6\1\0\4\6\3\0\2\6\1\0\1\6\1\0"+
    "\2\6\3\0\2\6\3\0\3\6\3\0\14\6\4\0\5\11\3\0"+
    "\3\11\1\0\4\11\2\0\1\6\6\0\1\11\16\0\12\11\11\0"+
    "\1\6\7\0\3\11\1\0\10\6\1\0\3\6\1\0\27\6\1\0"+
    "\12\6\1\0\5\6\3\0\1\6\7\11\1\0\3\11\1\0\4\11"+
    "\7\0\2\11\1\0\2\6\6\0\2\6\2\11\2\0\12\11\22\0"+
    "\2\11\1\0\10\6\1\0\3\6\1\0\27\6\1\0\12\6\1\0"+
    "\5\6\2\0\1\11\1\6\7\11\1\0\3\11\1\0\4\11\7\0"+
    "\2\11\7\0\1\6\1\0\2\6\2\11\2\0\12\11\1\0\2\6"+
    "\17\0\2\11\1\0\10\6\1\0\3\6\1\0\51\6\2\0\1\6"+
    "\7\11\1\0\3\11\1\0\4\11\1\6\10\0\1\11\10\0\2\6"+
    "\2\11\2\0\12\11\12\0\6\6\2\0\2\11\1\0\22\6\3\0"+
    "\30\6\1\0\11\6\1\0\1\6\2\0\7\6\3\0\1\11\4\0"+
    "\6\11\1\0\1\11\1\0\10\11\22\0\2\11\15\0\60\6\1\11"+
    "\2\6\7\11\4\0\10\6\10\11\1\0\12\11\47\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\0\1\6\2\0\1\6\6\0\4\6\1\0"+
    "\7\6\1\0\3\6\1\0\1\6\1\0\1\6\2\0\2\6\1\0"+
    "\4\6\1\11\2\6\6\11\1\0\2\11\1\6\2\0\5\6\1\0"+
    "\1\6\1\0\6\11\2\0\12\11\2\0\4\6\40\0\1\6\27\0"+
    "\2\11\6\0\12\11\13\0\1\11\1\0\1\11\1\0\1\11\4\0"+
    "\2\11\10\6\1\0\44\6\4\0\24\11\1\0\2\11\5\6\13\11"+
    "\1\0\44\11\11\0\1\11\71\0\53\6\24\11\1\6\12\11\6\0"+
    "\6\6\4\11\4\6\3\11\1\6\3\11\2\6\7\11\3\6\4\11"+
    "\15\6\14\11\1\6\17\11\2\0\46\6\1\0\1\6\5\0\1\6"+
    "\2\0\53\6\1\0\u014d\6\1\0\4\6\2\0\7\6\1\0\1\6"+
    "\1\0\4\6\2\0\51\6\1\0\4\6\2\0\41\6\1\0\4\6"+
    "\2\0\7\6\1\0\1\6\1\0\4\6\2\0\17\6\1\0\71\6"+
    "\1\0\4\6\2\0\103\6\2\0\3\11\40\0\20\6\20\0\125\6"+
    "\14\0\u026c\6\2\0\21\6\1\0\32\6\5\0\113\6\3\0\3\6"+
    "\17\0\15\6\1\0\4\6\3\11\13\0\22\6\3\11\13\0\22\6"+
    "\2\11\14\0\15\6\1\0\3\6\1\0\2\11\14\0\64\6\40\11"+
    "\3\0\1\6\3\0\2\6\1\11\2\0\12\11\41\0\3\11\2\0"+
    "\12\11\6\0\130\6\10\0\51\6\1\11\1\6\5\0\106\6\12\0"+
    "\35\6\3\0\14\11\4\0\14\11\12\0\12\11\36\6\2\0\5\6"+
    "\13\0\54\6\4\0\21\11\7\6\2\11\6\0\12\11\46\0\27\6"+
    "\5\11\4\0\65\6\12\11\1\0\35\11\2\0\13\11\6\0\12\11"+
    "\15\0\1\6\130\0\5\11\57\6\21\11\7\6\4\0\12\11\21\0"+
    "\11\11\14\0\3\11\36\6\15\11\2\6\12\11\54\6\16\11\14\0"+
    "\44\6\24\11\10\0\12\11\3\0\3\6\12\11\44\6\122\0\3\11"+
    "\1\0\25\11\4\6\1\11\4\6\3\11\2\6\11\0\300\6\47\11"+
    "\25\0\4\11\u0116\6\2\0\6\6\2\0\46\6\2\0\6\6\2\0"+
    "\10\6\1\0\1\6\1\0\1\6\1\0\1\6\1\0\37\6\2\0"+
    "\65\6\1\0\7\6\1\0\1\6\3\0\3\6\1\0\7\6\3\0"+
    "\4\6\2\0\6\6\4\0\15\6\5\0\3\6\1\0\7\6\16\0"+
    "\5\11\30\0\1\42\1\42\5\11\20\0\2\6\23\0\1\6\13\0"+
    "\5\11\5\0\6\11\1\0\1\6\15\0\1\6\20\0\15\6\3\0"+
    "\33\6\25\0\15\11\4\0\1\11\3\0\14\11\21\0\1\6\4\0"+
    "\1\6\2\0\12\6\1\0\1\6\3\0\5\6\6\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\4\6\1\0\13\6\2\0\4\6\5\0"+
    "\5\6\4\0\1\6\21\0\51\6\u0a77\0\57\6\1\0\57\6\1\0"+
    "\205\6\6\0\4\6\3\11\2\6\14\0\46\6\1\0\1\6\5\0"+
    "\1\6\2\0\70\6\7\0\1\6\17\0\1\11\27\6\11\0\7\6"+
    "\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6"+
    "\1\0\7\6\1\0\7\6\1\0\40\11\57\0\1\6\u01d5\0\3\6"+
    "\31\0\11\6\6\11\1\0\5\6\2\0\5\6\4\0\126\6\2\0"+
    "\2\11\2\0\3\6\1\0\132\6\1\0\4\6\5\0\51\6\3\0"+
    "\136\6\21\0\33\6\65\0\20\6\u0200\0\u19b6\6\112\0\u51cd\6\63\0"+
    "\u048d\6\103\0\56\6\2\0\u010d\6\3\0\20\6\12\11\2\6\24\0"+
    "\57\6\1\11\4\0\12\11\1\0\31\6\7\0\1\11\120\6\2\11"+
    "\45\0\11\6\2\0\147\6\2\0\4\6\1\0\4\6\14\0\13\6"+
    "\115\0\12\6\1\11\3\6\1\11\4\6\1\11\27\6\5\11\20\0"+
    "\1\6\7\0\64\6\14\0\2\11\62\6\21\11\13\0\12\11\6\0"+
    "\22\11\6\6\3\0\1\6\4\0\12\11\34\6\10\11\2\0\27\6"+
    "\15\11\14\0\35\6\3\0\4\11\57\6\16\11\16\0\1\6\12\11"+
    "\46\0\51\6\16\11\11\0\3\6\1\11\10\6\2\11\2\0\12\11"+
    "\6\0\27\6\3\0\1\6\1\11\4\0\60\6\1\11\1\6\3\11"+
    "\2\6\2\11\5\6\2\11\1\6\1\11\1\6\30\0\3\6\2\0"+
    "\13\6\5\11\2\0\3\6\2\11\12\0\6\6\2\0\6\6\2\0"+
    "\6\6\11\0\7\6\1\0\7\6\221\0\43\6\10\11\1\0\2\11"+
    "\2\0\12\11\6\0\u2ba4\6\14\0\27\6\4\0\61\6\u2104\0\u016e\6"+
    "\2\0\152\6\46\0\7\6\14\0\5\6\5\0\1\6\1\11\12\6"+
    "\1\0\15\6\1\0\5\6\1\0\1\6\1\0\2\6\1\0\2\6"+
    "\1\0\154\6\41\0\u016b\6\22\0\100\6\2\0\66\6\50\0\15\6"+
    "\3\0\20\11\20\0\7\11\14\0\2\6\30\0\3\6\31\0\1\6"+
    "\6\0\5\6\1\0\207\6\2\0\1\11\4\0\1\6\13\0\12\11"+
    "\7\0\32\6\4\0\1\6\1\0\32\6\13\0\131\6\3\0\6\6"+
    "\2\0\6\6\2\0\6\6\2\0\3\6\3\0\2\6\3\0\2\6"+
    "\22\0\3\11\4\0\14\6\1\0\32\6\1\0\23\6\1\0\2\6"+
    "\1\0\17\6\2\0\16\6\42\0\173\6\105\0\65\6\210\0\1\11"+
    "\202\0\35\6\3\0\61\6\57\0\37\6\21\0\33\6\65\0\36\6"+
    "\2\0\44\6\4\0\10\6\1\0\5\6\52\0\236\6\2\0\12\11"+
    "\u0356\0\6\6\2\0\1\6\1\0\54\6\1\0\2\6\3\0\1\6"+
    "\2\0\27\6\252\0\26\6\12\0\32\6\106\0\70\6\6\0\2\6"+
    "\100\0\1\6\3\11\1\0\2\11\5\0\4\11\4\6\1\0\3\6"+
    "\1\0\33\6\4\0\3\11\4\0\1\11\40\0\35\6\203\0\66\6"+
    "\12\0\26\6\12\0\23\6\215\0\111\6\u03b7\0\3\11\65\6\17\11"+
    "\37\0\12\11\20\0\3\11\55\6\13\11\2\0\1\11\22\0\31\6"+
    "\7\0\12\11\6\0\3\11\44\6\16\11\1\0\12\11\100\0\3\11"+
    "\60\6\16\11\4\6\13\0\12\11\u04a6\0\53\6\15\11\10\0\12\11"+
    "\u0936\0\u036f\6\221\0\143\6\u0b9d\0\u042f\6\u33d1\0\u0239\6\u04c7\0\105\6"+
    "\13\0\1\6\56\11\20\0\4\11\15\6\u4060\0\2\6\u2163\0\5\11"+
    "\3\0\26\11\2\0\7\11\36\0\4\11\224\0\3\11\u01bb\0\125\6"+
    "\1\0\107\6\1\0\2\6\2\0\1\6\2\0\2\6\2\0\4\6"+
    "\1\0\14\6\1\0\1\6\1\0\7\6\1\0\101\6\1\0\4\6"+
    "\2\0\10\6\1\0\7\6\1\0\34\6\1\0\4\6\1\0\5\6"+
    "\1\0\1\6\3\0\7\6\1\0\u0154\6\2\0\31\6\1\0\31\6"+
    "\1\0\37\6\1\0\31\6\1\0\37\6\1\0\31\6\1\0\37\6"+
    "\1\0\31\6\1\0\37\6\1\0\31\6\1\0\10\6\2\0\62\11"+
    "\u1600\0\4\6\1\0\33\6\1\0\2\6\1\0\1\6\2\0\1\6"+
    "\1\0\12\6\1\0\4\6\1\0\1\6\1\0\1\6\6\0\1\6"+
    "\4\0\1\6\1\0\1\6\1\0\1\6\1\0\3\6\1\0\2\6"+
    "\1\0\1\6\2\0\1\6\1\0\1\6\1\0\1\6\1\0\1\6"+
    "\1\0\1\6\1\0\2\6\1\0\1\6\2\0\4\6\1\0\7\6"+
    "\1\0\4\6\1\0\4\6\1\0\1\6\1\0\12\6\1\0\21\6"+
    "\5\0\3\6\1\0\5\6\1\0\21\6\u1144\0\ua6d7\6\51\0\u1035\6"+
    "\13\0\336\6\u3fe2\0\u021e\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\11\36\0\140\11\200\0\360\11\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\4\1\5\1\1\6\2"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\2\1\1\1\2\1\6\7\0\4\2\1\16\1\17"+
    "\1\2\1\0\1\16\1\20\11\0\3\2\1\21\2\2"+
    "\1\22\1\23\1\24\1\0\1\25\1\0\1\26\1\27"+
    "\1\30\5\2\1\31\1\32\1\33\1\34\2\2\1\35"+
    "\1\36\1\37\1\2\1\40\1\41";

  private static int [] zzUnpackAction() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\112\0\157\0\112\0\224\0\112\0\271"+
    "\0\336\0\u0103\0\u0128\0\u014d\0\u0172\0\u0197\0\u01bc\0\112"+
    "\0\112\0\112\0\112\0\112\0\112\0\112\0\112\0\u01e1"+
    "\0\u0206\0\u022b\0\u0206\0\u0250\0\u0275\0\u029a\0\u02bf\0\u02e4"+
    "\0\u0309\0\u032e\0\u0353\0\u0378\0\u039d\0\u03c2\0\157\0\157"+
    "\0\u03e7\0\u0206\0\u01e1\0\u0250\0\u040c\0\u0431\0\u0456\0\u047b"+
    "\0\u04a0\0\u04c5\0\u04ea\0\u050f\0\u0534\0\u0559\0\u057e\0\u05a3"+
    "\0\u05c8\0\u05ed\0\u0612\0\112\0\112\0\112\0\u0637\0\112"+
    "\0\u065c\0\112\0\112\0\112\0\u0681\0\u06a6\0\u06cb\0\u06f0"+
    "\0\u0715\0\157\0\157\0\112\0\112\0\u073a\0\u075f\0\112"+
    "\0\157\0\157\0\u0784\0\112\0\157";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\3\1\4\1\10"+
    "\1\11\1\3\1\12\1\13\4\4\1\14\1\4\1\15"+
    "\1\16\1\4\1\17\3\4\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\4\1\3\1\7\2\3"+
    "\1\30\1\5\1\6\1\7\1\31\1\4\1\10\1\11"+
    "\1\3\1\12\1\13\4\4\1\14\1\4\1\32\1\16"+
    "\1\4\1\17\3\4\1\33\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\4\1\3\1\7\1\3\46\0"+
    "\1\4\4\0\2\4\1\0\20\4\10\0\1\4\2\0"+
    "\1\4\2\0\1\5\51\0\1\10\1\34\50\0\1\35"+
    "\1\36\1\37\1\0\1\40\1\41\5\0\1\42\16\0"+
    "\1\4\4\0\2\4\1\0\2\4\1\43\15\4\10\0"+
    "\1\4\2\0\1\4\1\0\1\4\4\0\2\4\1\0"+
    "\7\4\1\44\10\4\10\0\1\4\2\0\1\4\1\0"+
    "\1\4\4\0\2\4\1\0\10\4\1\45\5\4\1\46"+
    "\1\4\10\0\1\4\2\0\1\4\1\0\1\4\4\0"+
    "\2\4\1\0\3\4\1\47\14\4\10\0\1\4\2\0"+
    "\1\4\1\0\1\4\4\0\2\4\1\0\13\4\1\50"+
    "\4\4\10\0\1\4\2\0\1\4\1\0\1\4\4\0"+
    "\2\4\1\0\15\4\1\51\2\4\10\0\1\4\2\0"+
    "\1\4\1\52\1\30\1\7\1\0\2\52\2\30\1\52"+
    "\20\30\10\52\1\30\2\0\1\4\2\52\1\7\1\0"+
    "\36\52\3\0\1\52\1\30\1\7\1\0\2\52\2\30"+
    "\1\52\3\30\1\53\14\30\10\52\1\30\2\0\1\4"+
    "\7\0\1\54\50\0\1\55\51\0\1\56\4\0\1\57"+
    "\40\0\1\60\64\0\1\61\17\0\1\62\3\0\1\63"+
    "\44\0\1\64\4\0\1\65\20\0\1\4\4\0\2\4"+
    "\1\0\3\4\1\66\6\4\1\67\5\4\10\0\1\4"+
    "\2\0\1\4\1\0\1\4\4\0\2\4\1\0\5\4"+
    "\1\70\12\4\10\0\1\4\2\0\1\4\1\0\1\4"+
    "\4\0\2\4\1\0\11\4\1\71\6\4\10\0\1\4"+
    "\2\0\1\4\1\0\1\4\4\0\2\4\1\0\17\4"+
    "\1\72\10\0\1\4\2\0\1\4\1\0\1\4\4\0"+
    "\2\4\1\0\7\4\1\73\10\4\10\0\1\4\2\0"+
    "\1\4\10\0\1\74\44\0\1\75\44\0\1\76\56\0"+
    "\1\77\32\0\1\100\61\0\1\101\27\0\1\102\44\0"+
    "\1\103\44\0\1\104\35\0\1\4\4\0\2\4\1\0"+
    "\4\4\1\105\13\4\10\0\1\4\2\0\1\4\1\0"+
    "\1\4\4\0\2\4\1\0\10\4\1\106\7\4\10\0"+
    "\1\4\2\0\1\4\1\0\1\4\4\0\2\4\1\0"+
    "\11\4\1\107\6\4\10\0\1\4\2\0\1\4\1\0"+
    "\1\4\4\0\2\4\1\0\11\4\1\110\1\111\5\4"+
    "\10\0\1\4\2\0\1\4\1\0\1\4\4\0\2\4"+
    "\1\0\7\4\1\112\10\4\10\0\1\4\2\0\1\4"+
    "\1\0\1\4\4\0\2\4\1\0\10\4\1\113\7\4"+
    "\10\0\1\4\2\0\1\4\10\0\1\114\44\0\1\115"+
    "\35\0\1\4\4\0\2\4\1\0\2\4\1\116\15\4"+
    "\10\0\1\4\2\0\1\4\1\0\1\4\4\0\2\4"+
    "\1\0\14\4\1\117\3\4\10\0\1\4\2\0\1\4"+
    "\1\0\1\4\4\0\2\4\1\0\20\4\1\120\7\0"+
    "\1\4\2\0\1\4\1\0\1\4\4\0\2\4\1\0"+
    "\3\4\1\121\14\4\10\0\1\4\2\0\1\4\1\0"+
    "\1\4\4\0\2\4\1\0\13\4\1\122\4\4\10\0"+
    "\1\4\2\0\1\4\1\0\1\4\4\0\2\4\1\0"+
    "\5\4\1\123\12\4\10\0\1\4\2\0\1\4\1\0"+
    "\1\4\4\0\2\4\1\0\20\4\1\124\7\0\1\4"+
    "\2\0\1\4\1\0\1\4\4\0\2\4\1\0\6\4"+
    "\1\125\11\4\10\0\1\4\2\0\1\4";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1961];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\1\1\1\11\10\1\10\11"+
    "\4\1\7\0\7\1\1\0\2\1\11\0\6\1\3\11"+
    "\1\0\1\11\1\0\3\11\7\1\2\11\2\1\1\11"+
    "\3\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	private void print(String s){
		System.out.println(s);
	}

	private void symbol(LexicalUnit type){
		System.out.println((new Symbol(type, yyline+1, yycolumn+1,yytext())).toString());
	}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexicalAnalyser(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2828) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.print(yytext());
            }
          case 34: break;
          case 2: 
            { symbol(LexicalUnit.VARNAME);
            }
          case 35: break;
          case 3: 
            { symbol(LexicalUnit.ENDLINE);
            }
          case 36: break;
          case 4: 
            { 
            }
          case 37: break;
          case 5: 
            { symbol(LexicalUnit.INTEGER);
            }
          case 38: break;
          case 6: 
            { symbol(LexicalUnit.TIMES);
            }
          case 39: break;
          case 7: 
            { symbol(LexicalUnit.COMMA);
            }
          case 40: break;
          case 8: 
            { symbol(LexicalUnit.LEFT_PARENTHESIS);
            }
          case 41: break;
          case 9: 
            { symbol(LexicalUnit.RIGHT_PARENTHESIS);
            }
          case 42: break;
          case 10: 
            { symbol(LexicalUnit.EQUAL);
            }
          case 43: break;
          case 11: 
            { symbol(LexicalUnit.MINUS);
            }
          case 44: break;
          case 12: 
            { symbol(LexicalUnit.PLUS);
            }
          case 45: break;
          case 13: 
            { symbol(LexicalUnit.DIVIDE);
            }
          case 46: break;
          case 14: 
            { symbol(LexicalUnit.DO);
            }
          case 47: break;
          case 15: 
            { symbol(LexicalUnit.IF);
            }
          case 48: break;
          case 16: 
            { symbol(LexicalUnit.NUMBER);
            }
          case 49: break;
          case 17: 
            { symbol(LexicalUnit.END);
            }
          case 50: break;
          case 18: 
            { symbol(LexicalUnit.OR);
            }
          case 51: break;
          case 19: 
            { symbol(LexicalUnit.GREATER_EQUAL);
            }
          case 52: break;
          case 20: 
            { symbol(LexicalUnit.GREATER);
            }
          case 53: break;
          case 21: 
            { symbol(LexicalUnit.EQUAL_COMPARE);
            }
          case 54: break;
          case 22: 
            { symbol(LexicalUnit.DIFFERENT);
            }
          case 55: break;
          case 23: 
            { symbol(LexicalUnit.SMALLER_EQUAL);
            }
          case 56: break;
          case 24: 
            { symbol(LexicalUnit.SMALLER);
            }
          case 57: break;
          case 25: 
            { symbol(LexicalUnit.ELSE);
            }
          case 58: break;
          case 26: 
            { symbol(LexicalUnit.THEN);
            }
          case 59: break;
          case 27: 
            { symbol(LexicalUnit.AND);
            }
          case 60: break;
          case 28: 
            { symbol(LexicalUnit.NOT);
            }
          case 61: break;
          case 29: 
            { symbol(LexicalUnit.READ);
            }
          case 62: break;
          case 30: 
            { symbol(LexicalUnit.ENDDO);
            }
          case 63: break;
          case 31: 
            { symbol(LexicalUnit.ENDIF);
            }
          case 64: break;
          case 32: 
            { symbol(LexicalUnit.PRINT);
            }
          case 65: break;
          case 33: 
            { symbol(LexicalUnit.PROGRAM);
            }
          case 66: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java LexicalAnalyser [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        LexicalAnalyser scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new LexicalAnalyser(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
